name: Deploy VPN

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Region to deploy VPN'
        required: true
        default: nyc3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="do_token=${{ secrets.DIGITALOCEAN_TOKEN }}" \
            -var="ssh_fingerprint=b2:5f:b6:f8:09:e2:91:fd:39:2c:9e:e2:c8:65:a6:9d" \
            -var="region=${{ github.event.inputs.region }}" \
            -var="droplet_name=wg-vpn" \
            -input=false

      - name: VPN IP
        run: |
          IP=$(terraform output -raw vpn_ip)
          echo "${IP%%:*}"
