name: Destroy VPN

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
    steps:
      - name: Destroy active VPN droplet
        run: |
          DROPLET_NAME="${{ github.event.inputs.droplet_name }}"
          DROPLET_ID=$(curl -s -X GET \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
            "https://api.digitalocean.com/v2/droplets" \
            | jq -r --arg name "$DROPLET_NAME" '.droplets[] | select(.name==$name) | .id')
          
          if [ -n "$DROPLET_ID" ]; then
            curl -s -X DELETE \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" \
              "https://api.digitalocean.com/v2/droplets/$DROPLET_ID"
            echo "Droplet $DROPLET_ID destroyed."
          else
            echo "No droplet found to destroy."
          fi
